name: kidasie

services:
    postgres:
      image: postgres:18.4
      restart: unless-stopped
      shm_size: 128mb

      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

      ports:
        - "127.0.0.1:5432:5432"

      volumes:
        - postgres_data:/var/lib/postgresql

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 5s
        timeout: 5s
        retries: 5

volumes:
    postgres_data:

